export default {
  CHROME_EXTENSION: "hermes-io-devtools",
  CONTEXT_SNAPSHOT: "CONTEXT_SNAPSHOT",
  START_RECORDING: "START_RECORDING",
  STOP_RECORDING: "STOP_RECORDING",
  SET_CONTEXT: "SET_CONTEXT",
  LOAD_RECORDING: "LOAD_RECORDING",
  RESET_RECORDING: "RESET_RECORDING",
} 
